# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170205_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
