# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170206_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('url', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
