# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(unique=True)),
                ('provider', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_at', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('ordering', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
