# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20170204_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(unique=True),
        ),
    ]
