# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20170204_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
