# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20170204_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
